### ISSUE TITLE
🐛 Bug Report: Character count covers "Add item" button

### ISSUE THREAD

**Issue by tejender** [appwrite/console#1041]
when we select an attribute type as an array, to add items in array we get option of 'add item' to new item in existing array. But im not getting that option after adding one item.

This only happening when the attribute size is set such that you get text area to add value in attribute instead of single line text field.

I  thinks it is a interface/styling issue as i tried to search 'add item' to see the button is present, and it is giving me match but the button is not vissible. 
<img width="1421" alt="Screenshot 2024-04-14 at 4 42 37 PM" src="https://github.com/appwrite/appwrite/assets/6606484/b6b8e2d9-f8f4-4af8-a0e7-8de6923bdd02">
<img width="1421" alt="Screenshot 2024-04-14 at 4 42 18 PM" src="https://github.com/appwrite/appwrite/assets/6606484/38047866-a3b8-4881-a080-266fbfecc7e3">

**Comment by stnguyen90** [comment]
@tejender, thanks for raising this issue! We'll look into this soon.

**Comment by stnguyen90** [comment]
This was a bug in [Pink](https://github.com/appwrite/pink) and will be fixed after we bump pink in [this commit](https://github.com/appwrite/console/pull/1019/commits/c86211e974ee01698e23bc5395419f7cbd349e20).

**Comment by stnguyen90** [comment]
Fixed in 1.5.5: 

![Image](https://github.com/appwrite/console/assets/1477010/6f4287b5-2b98-43e4-a34f-11cbfb6831ef)

**Comment by tejender** [comment]
I've checked it, and this issue is still there

**Comment by tejender** [comment]
> Fixed in 1.5.5: 
> 
> ![Image](https://github.com/appwrite/console/assets/1477010/6f4287b5-2b98-43e4-a34f-11cbfb6831ef)
> 
> 

I've checked it and this issue is still there 
![IMG-20240430-WA0000.jpg](https://github.com/appwrite/console/assets/6606484/6ec0d62c-f3c1-44ac-be8d-b0175eb94532)

![IMG-20240430-WA0001.jpg](https://github.com/appwrite/console/assets/6606484/9e2f92cf-fa63-40e3-ae7d-e2937254d1a8)

**Comment by tejender** [comment]
Further more updates.. In one collection i have attributes thumbnails, slug.where thumbnail is array of string type.three its working as expected.. In other collection i jave multiple attributes and in between there is one again of array of string and there I'm facing the same issue..This needs ro be tested for multiple layout styles
