### ISSUE TITLE
🐛 Bug Report: Issue with default Auth Email Templates

### ISSUE THREAD

**Issue by mdorchain** [appwrite/console#2106]
### 👟 Reproduction steps

Since the version 1.6.2 (self hosted), when I open the templates, the subject and message loaded is the same for all emails and matches the Verification email.

<img width="1788" height="5827" alt="Image" src="https://github.com/user-attachments/assets/1e3a2a94-5ccc-4408-81be-1f03cc18d1b0" />

### 👍 Expected behavior

Emails should display their own template.

### 👎 Actual Behavior

By default the Verification email is displayed for all the emails.

Modifying any email only modifies the Verification email but reflects on all the emails.

Doing a Reset Changes doesn't help, they already have the default templates.

The email sent are using the proper the proper template (not the one showing), so it's just a matter of UI in the console.

Checking the http requests, I only see a single call to https://example.com/v1/projects/xxxxx/templates/email/verification/en

I can reproduce the issue on 2 self hosted instances (version 1.6.2 and 1.7.4) but I don't see it on my cloud account.
Could it be a migration issue? If so how can I fix it?

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Version 1.7.4

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by tejas-raskar** [comment]
Is this with a custom SMTP setup? I tried to recreate the bug, but the templates loaded as expected. Am I missing something? I am using 1.7.4

https://github.com/user-attachments/assets/a695c4e2-64e3-481b-a136-8ccdcaad57b0

**Comment by mdorchain** [comment]
Yes it's with the custom smtp on 1.6 2 and 1.7.4.
I suspect a migration issue at some point.
I reinstalled the 1.7.4 on both self hosted instance but no luck. Clicking on a different email does not fetch its content.

**Comment by stnguyen90** [comment]
I'm pretty sure this as fixed by https://github.com/appwrite/console/pull/1940

**Comment by disguized** [comment]
Hi @mdorchain, did it resolve for you?

**Comment by disguized** [comment]
The issue is still there, I had installed 1.7.4, reinstalled, ran migrations, still the same

**Comment by mdorchain** [comment]
It's not fixed in the current version. Even on a clean 1.7.4, it's the same issue.
The fix was merged after the 1.7.4 release. So we'll have to wait until the next one.

**Comment by disguized** [comment]
when is the next release scheduled?

**Comment by disguized** [comment]
> It's not fixed in the current version. Even on a clean 1.7.4, it's the same issue. The fix was merged after the 1.7.4 release. So we'll have to wait until the next one.

but it is not there with cloud

**Comment by disguized** [comment]
> It's not fixed in the current version. Even on a clean 1.7.4, it's the same issue. The fix was merged after the 1.7.4 release. So we'll have to wait until the next one.

and more funny and interesting is that both cloud and self hosted have same version

**Comment by kodejuice** [comment]
I solved this by modifying the data directly from my `appwrite` database

in the `_console_projects` table, the templates is under the `templates` column

Took a while to reflect in the console because of caching i guess
